dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard' 

urlpatterns = [
    path('homepage/', views.homepage, name='homepage'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include  # Importa anche include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('auth/', include(('two_factor_auth.urls', 'two_factor_auth'), namespace='two_factor_auth')),
    path('dashboard/', include('dashboard.urls', 'dashboard')),  # Includi le URL della tua app qui
    # Puoi aggiungere altre URL globali qui
]

two_factor_auth/urls.py
from django.urls import path
from .views import user_login, generate_qr_code,complete_config, verify_otp,verify_backup_otp,asp_user_logout, user_logout,send_otp_and_redirect,verify_token, get_user_email

app_name = 'two_factor_auth'

urlpatterns = [
    path('login/', user_login, name='login'),
    path('generate_qr/', generate_qr_code, name='generate_qr'),
    path('verify_otp/', verify_otp, name='verify_otp'),
    path('send_otp_and_redirect/', send_otp_and_redirect, name='send_otp_and_redirect'),
    path('verify_backup_otp/', verify_backup_otp, name='verify_backup_otp'),
    path('logout/', asp_user_logout, name='logout'),
    path('logout_base/', user_logout, name='logout_base'),
    path('verify-token/', verify_token, name='verify_token'),
    path('get_user_email/', get_user_email, name='get_user_email'),
    path('complete_config/', complete_config, name='complete_config'),  # Nuova route

]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

@login_required
def homepage(request):
    return render(request, 'homepage.html')
# Create your views here.

dashboard/templates/homepage.html
<!DOCTYPE html>
<html>
<head>
    <title>Homepage</title>
</head>
<body>
    <div class="navbar">
        <ul>
            
            <!-- Altri link della navbar se necessario -->
            <li><a href="{% url 'two_factor_auth:logout' %}" onclick="return confirm('Sei sicuro di voler uscire?');">Logout</a></li>
        </ul>
    </div>
    <h1>Benvenuto nella homepage!</h1>
    <!-- Aggiungi altro contenuto qui -->
</body>
</html>